version: "3"

services:
  database:
    image: bitnami/postgresql:latest
    container_name: database
    restart: always
    ports:
      - 5400:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=delivery
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3000:3000
      - 9000:9000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
